# Generated by Django 6.0.4 on 2026-05-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('date', models.DateField()),
                ('supplier', models.CharField(max_length=100)),
                ('specifications', models.CharField(max_length=100)),
            ],
        ),
    ]
