# Generated by Django 6.0.3 on 2026-05-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
    ]
