# Generated by Django 6.0.3 on 2026-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0002_alter_stock_cost_price_alter_stock_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='specifications',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
