# Generated by Django 6.0.4 on 2026-05-08 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='method_of_payment',
            field=models.CharField(default='Cash', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
