# Generated by Django 6.0.4 on 2026-05-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0006_customer_amount_customer_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='supplier',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
