# Generated by Django 6.0.4 on 2026-05-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0007_alter_stock_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='supplier',
        ),
    ]
