# Generated by Django 6.0.4 on 2026-05-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0008_remove_stock_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('method_of_payment', models.CharField(default='Cash', max_length=100)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mugeniapp.stock')),
            ],
        ),
    ]
