# Generated by Django 6.0.4 on 2026-05-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0009_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
