# Generated by Django 6.0.4 on 2026-05-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0010_customer_amount_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='amount_paid',
        ),
        migrations.AddField(
            model_name='supplier',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
