# Generated by Django 6.0.4 on 2026-05-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0011_remove_customer_amount_paid_supplier_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cost_price',
            field=models.IntegerField(),
        ),
    ]
