# Generated by Django 6.0.4 on 2026-05-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0012_alter_supplier_amount_paid_alter_supplier_cost_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
