# Generated by Django 6.0.4 on 2026-05-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0013_sales_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='unit_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='cost_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='selling_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cost_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
