# Generated by Django 6.0.4 on 2026-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0014_alter_customer_amount_alter_sales_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='grand_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sales',
            name='transport_fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
