# Generated by Django 6.0.4 on 2026-05-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0015_sales_distance_sales_grand_total_sales_transport_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_cost',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
