# Generated by Django 6.0.4 on 2026-05-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0016_supplier_balance_supplier_supplier_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='method_of_payment',
        ),
    ]
