# Generated by Django 6.0.4 on 2026-05-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0018_alter_customer_amount_alter_supplier_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='method_of_payment',
            field=models.CharField(default='Credit', max_length=50),
        ),
    ]
