# Generated by Django 6.0.4 on 2026-05-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0019_supplier_method_of_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='stock',
        ),
        migrations.AddField(
            model_name='supplier',
            name='product_name',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
