# Generated by Django 6.0.4 on 2026-05-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0020_remove_supplier_stock_supplier_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='supplier',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
