# Generated by Django 6.0.3 on 2026-05-29 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mugeniapp', '0022_alter_stock_name_alter_stock_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='specifications',
        ),
    ]
